### ISSUE TITLE
IPhone port

### ISSUE THREAD

**Issue by rmcpantoja** [IhorShevchuk/RHVoice-spm#1]
Hi,
What progress do you have supporting this in IOS, like Voice over screen reader? Or are you planning to do it?
I would like to use my custom packages.json with my private languages/voices for personal use, as in Android.
Cheers.

**Comment by IhorShevchuk** [comment]
Hi,
There is already RHVoice application for iOS: https://apps.apple.com/us/app/rhvoice/id6444378148, 
I don't have plans to create clone application to integrate it with iOS Voiceover reader.

Feel free to use this repository for personal use, however keep in mind licensing perspective. 

Purpose of this repository is to simplify building self speaking applications.

**Comment by IhorShevchuk** [comment]
Closing the issue since there were no discussion made during last few month.
